{"sid": "7e9e2624e3564b0297b064ff11f80e05", "uid": null, "qid": "3026d3b028b840e891fef19492b9aeef", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [3026d3b028b840e891fef19492b9aeef]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 59, in execute\n    return self.execution_function(input, ray, state)\nTypeError: 'NoneType' object is not callable\n", "created_at": "2025-06-21T17:17:21.943082"}], "status": "FAILED", "created_at": "2025-06-21T17:17:21.801465", "updated_at": "2025-06-21T17:17:21.943116", "finished": true}